### PR TITLE
Improve visibility selector.

### PR DESCRIPTION
**Pull request by n1k0**

### CODE REVIEW

**Comment by n1k0** [comment]
> Maybe put public first on the left? As it's the most used, I think it would make sense to have it first in the list.

Funny, I put it last on purpose because then it's next to the Toot button. I don't have a strong opinion here, ping @DirtyF :p

**Comment by nicosomb** [comment]
* You can maybe move the NSFW checkbox at the top (near the spoiler one)
* the counter is too important I think. We can reduce it.

**Comment by vjousse** [comment]
Ahah @n1k0 nice :D 
So put switch the toot and clear buttons, and we're good to go :p

**Comment by n1k0** [comment]
Argh, I've always preferred having the action button on the right :/

**Comment by DirtyF** [comment]
> Funny, I put it last on purpose because then it's next to the Toot button. 

If you think mobile and finger gestures, that makes totally sense. 

As long as public is selected by default this does not matter so much here IMHO. I understand it as a hierarchy from left to right as more and more public.

> I've always preferred having the action button on the right :/

Yup, because we read from left to right, and call to action is like the point in a sentence, it comes at the end.

So I'm down with @n1k0 here, it only lacks an action color on the toot button to avoid cognitive effort.

For example on mamot.fr it's clear what the default action is:
capture d ecran 2017-05-03 a 16 05 34

**Comment by n1k0** [comment]
> it only lacks an action color on the toot button to avoid cognitive effort

I used the `btn-primary` class from bootstrap, but it's light grey, not *primary* enough indeed. What color do you suggest? Remember:

- I'm color blind
- We don't want to look too much like the official Web client

**Comment by n1k0** [comment]
There's these `btn-success`, `btn-warning` and `btn-info` colors available. Which one do you prefer?

### `btn-success`



### `btn-info`



### `btn-warning`



Another color?

**Comment by n1k0** [comment]
I'm gonna land this with the current style. Feel free to reopen if you have other opinions.

**Pull request merged**
