### PR TITLE
Add Docker support

### PR DESCRIPTION
**Pull request by valentin2105**
Hello ! 

I create a Docker file based on Debian jessie that run Tooty and Nginx to expose him.

I had the Documentation part too, to build the image and run tooty.

### CODE REVIEW

**Comment by valentin2105** [comment]
I switched from debian jessie to debian:stretch-slim and add the code from the repository instead of cloning it from github. 

The image size is 296MB.

**Comment by vjousse** [comment]
Thanks for the work!

It's maybe a silly question, but why bothering setting up a full nginx when the only thing it does is forwarding the request to the npm webserver?

**Comment by valentin2105** [comment]
I don't find the way to make Tooty bind on 0.0.0.0 rather than localhost. And if Tooty bind in localhost of the container, not any other container or Docker host can access to the container's network. 

Si I put a small nginx in front to make access clean to localhost:8000 of the container. 
To make it more secure, I suggest to expose this container behind a TLS reverse-proxy, for sure.

**Comment by n1k0** [comment]
As I'm not a docker user myself, I don't see myself maintaining this feature I have no personal use of. Though I understand that it could be useful to actual docker users, so that'd be great to have it landing somewhere.

Which makes me think we should probably create a github org, where we could have a dedicated, small repo for it, and you would be the official maintainer of it. Deal?

**Comment by valentin2105** [comment]
@n1k0 Yeah, if you prefer to separate the things, it make sense. 

Few project directly put the Dockerfile on the main repo too, to make it more visible for new users who want to deploy the project quickly. 

As you prefer ?!

**Comment by vjousse** [comment]
As mentioned above, I would prefer removing nginx instead of adding it for « nothing ».

You can change the line here: https://github.com/n1k0/tooty/blob/master/package.json#L11 by adding the `--host` option, something like: ` "start": "node_modules/.bin/elm-live src/Main.elm --host=0.0.0.0 --warn --dir=public/ --output=public/app.js",` should do the trick.

Could you give it a try?

**Comment by valentin2105** [comment]
@vjousse  Sorry for the placeholder, I have do the change in my fork (for my hosted Tooty) and I forgot this PR. I will rollback. 

About the aim of this Docker image, I was thinking about a easy way to deploy Tooty quickly in a "production" way. So as you say, I maybe don't need to launch `npm start` and only serve statics with Nginx. 

I will make few modifications soon.

**Comment by n1k0** [comment]
We're not gonna land this. Docker packaging should be handled in a dedicated repository if needed, as we don't plan nor have the time to maintain it in this one. Closing.

**Pull request closed without merging**
