### PR TITLE
WIP: Added option to show/hide 4th column

### PR DESCRIPTION
**Pull request by nicosomb**
issue #39 

Todo: 
- [X] add checkbox to show / hide the 4th column
- [ ] expand the other columns

### CODE REVIEW

**Comment by n1k0** [comment]
The main issue is where are we going to display profiles? And later, threads?

**Comment by nicosomb** [comment]
Oh I forgot that 🤔

**Comment by n1k0** [comment]
We could switch to relying on the notification column for that, which could then have a top tab menu to switch between notifications, thread, account, local and global timelines. But I liked the idea of always having Home and Notifications always visible in the UI...

**Comment by nicosomb** [comment]
I just tried this behavior: 
* hide the 4th column
* click on a username
* 🎉  the profile is displayed
* close the profile column
* the 4th column is still hidden

So, we just need to handle the size of the Home and Notifications columns. Right?

**Comment by n1k0** [comment]
> So, we just need to handle the size of the Home and Notifications columns. Right?

Hmm that sounds good. I'm gonna try the patch and see how it goes.

**Comment by n1k0** [comment]
So if we take that path, that will mean resizing column widths when viewing a user profile. Let's see how it comes out, but I suspect a jiggling UI might be annoying to use...

**Comment by nicosomb** [comment]
OK, so you think that it's better to have a *a top tab menu*?

**Comment by n1k0** [comment]
Yeah, but that becomes a little tricky to handle if we keep the idea of having an option to switch between 3 and 4 columns layout... 

I'd like feedback from other folks about this. /cc @vjousse @nsteinmetz

**Comment by j0k3r** [comment]
I don't like the jiggling UI too.
Maybe we can add an option to let user choose between auto-with column (and the jiggling) and fixed width column.
We can also hide the posting column by default.

**Comment by nsteinmetz** [comment]
Indeed, I forgot the utility of the 4th column to display user profile. So maybe only hiding 4th column (= being Local or global timeline) is enough ?

> Maybe we can add an option to let user choose between auto-with column (and the jiggling) and fixed width column.

Could be a good option.

> We can also hide the posting column by default.

Not a big fan of this one ; maybe then put 1st column (post column) as 1st row and for 2nd row a 3 column layout with home timeline, notification and whatever may be in the 3rd column ?

Or the post column being reduced on top left column and expand once you click on it to post a message ? May not the best UX as it requires an extra click :-/

**Comment by n1k0** [comment]
I suggest we close this as it has so much diverged from master that it's very unlikely this would ever land.

**Pull request closed without merging**
