### PR TITLE
Fix #152: Multiple accounts.

### LINKED ISSUE #152: Multiple accounts support
The only thing determining the requests to perform (and the data the app receives) is the `Client`. For now we store a single client for the app, and use it for everything.

Though it shouldn't be too hard to allow managing multiple clients, configured to deal with multiple user accounts (it doesn't even depend on the instance, as a client holds the server base URL).

If we can easily store multiple clients, offering multi-accounts support should be "just"¹ *matter of*:

- After registering with an instance, store the generated client into a list in localStorage.
- Associate user account info with a client; this will require updating the `Client` model to add an `Maybe Account` field (so we can list all registered identities). 
- Update the authorization flow to create a client from a received authCode. We're gonna use the saved registration for that.
- From the UI, allow adding more accounts by adding a link to register a new one (then reuse the auth form in a new dedicated view).
- In the UI, add a *Switch account* dropdown button and view to list all the registered accounts; clicking on one switches the app to use the matching stored client.
- When a different account is selected, reload all the timelines and user data.
- Store the last used client in localStorage, so we can load and init the app using that information.

Questions:

- Should we keep storing registrations forever? I feel like once an app instance is registered, we don't care about this information anymore (only the client bearer token is needed to authenticate requests). Otherwise if we do, we should store a list of matching registrations.

¹: *famous last words*

### PR DESCRIPTION
**Pull request by n1k0**
Refs #152, deployed to production. The only annoying thing is that when adding another account on an instance where you already have an authentication cookie set, there's no obvious way to bypass it and ask for signing in using another account.

Other than that, works fine.

### Todo

- [x] Fix empty black screen after first reauth
- [ ] Fix HTML5 auth form validation not working in Firefox 
- [x] When you click on *switch account*, the Mastodon server root URL field should be blank (not blank when you tried some URLs)

### CODE REVIEW

**Comment by nicosomb** [comment]
After a first login, I got a black screen. It was OK after hitting F5. 
capture d ecran 2017-05-09 a 11 21 02

**Comment by n1k0** [comment]
Yeah I had to update the format of the client stored in localStorage, basically we moved from a single client to a list of client, plus the client record now holds an `account` property.

I think it's fair to expect breakage like this one at this stage of the project :)

**Comment by nicosomb** [comment]
If you set a URL without `https`, it does nothing. I think that we should display an error (like the `unreachable host` one).

**Comment by n1k0** [comment]
> UX should evolve later when/if we want to support mobile usability.

Yeah, also the *switch account* link isn't visible enough, but I'm planning on iterating here (btw, if you have ideas...). Thanks for the feedback!

**Comment by DirtyF** [comment]
> the switch account link isn't visible enough, but I'm planning on iterating here (btw, if you have ideas...)

An accounts icon, should do it for now.

**Comment by n1k0** [comment]
As we already received good feedback about this feature, let's land this fat baby and spawn new issues for remaining work.

**Pull request merged**
