### PR TITLE
Fix #114: Close autocomplete menu when pressing Esc.

### LINKED ISSUE #114: Close autocomplete menu when pressing the Esc key
#107 follow up. We should listen to when the `Esc` key is pressed while the autocomplete menu is opened, and close it appropriately.

### PR DESCRIPTION
**Pull request by n1k0**
Deployed to prod. I'd like approval from @vjousse before landing this patch.

### CODE REVIEW

**Comment by n1k0** [comment]
It works for me on Firefox (I'm using 53.0).

**Comment by vjousse** [comment]
Can you give it a try with nightly?

**Comment by n1k0** [comment]
Works with Nightly 55.0a1 (2017-03-14), I'll update it to see if that broke recently.

**Comment by n1k0** [comment]
Works with very latest Nightly 55.0a1 (2017-05-06). I'm on Linux, could that be a Firefox bug on Mac?

**Comment by n1k0** [comment]
Maybe you have some faulty extension at play here?

Anyway, I'm gonna land this patch.

**Comment by vjousse** [comment]
I'm on Linux too, but I think that indeed, it's maybe due to my VimFx extension.
Great job :-)

**Pull request merged**
